Elasticsearch Particle
capitalone/Particle-Cloud-Framework pull request #135
Opened 2019-08-08 18:46 UTC by Bryantle1028

Implemented elasticsearch particle with tests in testdata.json and example_es_domain.py

2019-08-12 15:21 UTC, davidyum commented
I think you have a bunch of palcebo json files (96 for describe) from running record test multiple times. Could you just include one of each.

2019-08-12 15:27 UTC, bhl5kj commented
You have to delete all the useless describes that were returned while the particle was still spinning up. Remember I mentioned that you can just delete them and renumber the ones left over so that it skips over the 10 min spin up time.

2019-08-12 21:44 UTC, davidyum requested changes

2019-08-12 21:44 UTC, davidyum commented on examples/particle/aws/es/use_es/example_elasticsearch_domain.py
> +                'subnet-6bf0d333',
can you remove subnets. Use dummy values like subnet-1111111

2019-08-12 21:44 UTC, davidyum commented on examples/particle/aws/es/use_es/example_elasticsearch_domain.py
> +                'sg-2d991c57'
can you remove this too

2019-08-12 21:44 UTC, davidyum commented on examples/particle/aws/es/use_es/example_elasticsearch_domain.py
> +                'Value': 'janitorialservices@capitalone.com'
same with tags

2019-08-12 21:44 UTC, davidyum commented on examples/particle/aws/es/use_es/example_elasticsearch_domain.py
> +es_example_json['aws_resource']['Tags'][1]['Value'] = 'zhb257'
same here

2019-08-12 21:44 UTC, davidyum commented on pcf/particle/aws/es/es_domain.py
> +    This is the implementation of Amazon's S3 service.
change s3 to elasticsearch

2019-08-12 21:44 UTC, davidyum commented on pcf/particle/aws/es/es_domain.py
> +        Elasticsearch does not have a sotpped state so it calls terminate.
typo for stopped

2019-08-26 23:56 UTC, Bryantle1028 commented
> I think you have a bunch of palcebo json files (96 for describe) from running record test multiple times. Could you just include one of each.

2019-08-26 23:56 UTC, closed without merging

2019-08-27 00:00 UTC, Bryantle1028 commented
> I think you have a bunch of palcebo json files (96 for describe) from running record test multiple times. Could you just include one of each.

Should I just include one of each call even if some are not empty?

2019-08-27 14:43 UTC, brianhlee commented
Just delete everything in the folder and run generate once. Then go through and find the chunk of empty describe calls that are made while the particle is spinning up. This will make the test run faster without waiting the 10 mins it takes to spin it up.