Hosted zone Particle
capitalone/Particle-Cloud-Framework pull request #19
Opened 2018-12-10 23:10 UTC by bhl5kj

has the changes for security group PR because I forgot to branch for that one. I'll do it right next time

2018-12-13 16:22 UTC, anovis requested changes
minor changes, but otherwise looks good!

2018-12-13 16:22 UTC, anovis commented on examples/particle/aws/route53/use_route53/example_route53_hosted_zone.py
> +        "CallerReference": "werhasdkfboi12hasdfak",
make random string

2018-12-13 16:22 UTC, anovis commented on pcf/particle/aws/route53/route53_hosted_zone.py
> +class Route53HostedZone(AWSResource):
lets just call it HostedZone. and it would sit in the route53 folder.

2018-12-15 20:17 UTC, davidyum commented
Are there ways to add tags for hosted zone w/ boto3? 
Atleast in c1 I think they were enforcing tags at some point for hosted zone, not sure if its high priority outside but might be good to have

2018-12-17 15:06 UTC, bhl5kj commented
> Are there ways to add tags for hosted zone w/ boto3?
> Atleast in c1 I think they were enforcing tags at some point for hosted zone, not sure if its high priority outside but might be good to have
> @bhl5kj

will look into it, but they don't seem to have one after a quick look
they have an open issue asking for zone tagging

2018-12-19 16:11 UTC, anovis approved these changes

2018-12-19 16:12 UTC, merged