Just in Time Infrastructure example
capitalone/Particle-Cloud-Framework pull request #34
Opened 2019-01-14 16:05 UTC by anovis

#### Just in Time Infrastructure example
contains
- ec2
- vpc
- subnet
- security group
- instance profile

#### Bug Fix

- replace_value_nested_dict (works with list of strings now)
- find_value_nested_dict (works with list of strings now)
- aws_lookup (moved to apply so works with quasiparticle parents)

2019-01-19 10:15 UTC, anovis commented
will add application that can get triggered in the userda

2019-01-30 16:38 UTC, bhl5kj commented
LGTM

2019-01-30 16:45 UTC, jacoblearned requested changes
Small typos

2019-01-30 16:45 UTC, jacoblearned commented on examples/quasiparticle/aws/jit/README.md
> +the application. Check our docs for more infomation on JiTI and the benifits this provides.
`benifits` -> `benefits`

2019-01-30 16:46 UTC, jacoblearned commented on examples/quasiparticle/aws/jit/README.md
> +the application. Check our docs for more infomation on JiTI and the benifits this provides.
As well as `infomation`-> `information`

2019-02-01 18:32 UTC, jacoblearned approved these changes

2019-02-01 20:50 UTC, merged