Flask app
capitalone/Particle-Cloud-Framework pull request #35
Opened 2019-01-16 11:52 UTC by davidyum

Tried to keep the flask api example simple and in one file but let me know if we want a more "full" api as an example and add more stuff.

2019-01-17 14:57 UTC, anovis requested changes

2019-01-17 14:57 UTC, anovis commented on examples/flask_app/app.py
> +with open('higgs_example_config.json', 'r') as f:
remove higgs references

2019-01-17 14:57 UTC, anovis commented on examples/flask_app/higgs_example_config.json
> +        "multiplier": 2,
can we add optional param for user to pass in that would change multiplier.

2019-01-17 14:57 UTC, anovis commented on examples/flask_app/higgs_example_config.json
> +            "BlockDeviceMappings": [
dont need this for example

2019-01-17 14:57 UTC, anovis commented on examples/flask_app/requirements.txt
> +pcf
lets version these

2019-01-17 14:57 UTC, anovis commented on examples/flask_app/README.md
> +The purpose of this app is to show how to use PCF in a Flask api to spin up cloud resources. In this particular example we will utilize Capital One's Particle Cloud Framework to deploy ec2-route53 qu
the purpose of this example is to show one of multiple ways to use Particle Cloud Framework (PCF) to deploy cloud infrastructure which in this case is using a Flask api. In this particular example we deploy the ec2-route53 quasiparticle which creates a route53 record and adds the desired number on ec2 instances to the record set. to use in your environment  simply change some of the configurations parameters in the quasiparticle definition.

2019-01-17 14:57 UTC, anovis commented on examples/flask_app/README.md
> +Run Flask App Locally with Docker
interact with Flask App Locally?

2019-01-17 14:57 UTC, anovis commented on examples/flask_app/README.md
> +`curl -X POST http://localhost:5000/higgs`
change to pcf

2019-01-23 15:17 UTC, anovis requested changes

2019-01-23 15:17 UTC, anovis commented on examples/flask_app/app.py
> +        ec2_route53_quasiparticle = EC2Route53(pcf_config)
this is only defined here, so other endpoints dont work. the other endpoints should take in the pcf name and unique keys so you can get state and delete.

2019-01-23 15:17 UTC, anovis commented on examples/flask_app/app.py
> +    return str(ec2_route53_quasiparticle.get_state())
ec2_route53_quasiparticle not defined here...should create definition with only unique identifier to get state.

2019-01-23 15:17 UTC, anovis commented on examples/flask_app/app.py
> +    ec2_route53_quasiparticle.set_desired_state(State.terminated)
ec2_route53_quasiparticle not defined here...should create definition with only unique identifier to get Quasiparticle.

2019-02-05 10:50 UTC, davidyum commented
@anovis let me know if you get a chance to take a look at this one. Made the fixes

2019-02-05 14:01 UTC, anovis approved these changes

2019-02-05 14:02 UTC, merged