Pcf max timeout in apply()
capitalone/Particle-Cloud-Framework pull request #8
Opened 2018-11-23 21:04 UTC by emr0327

- added functionality for a max_timeout in apply() to prevent an infinite loop
- the user must pass the max_timeout integer in seconds as a keyword argument when calling the apply method

2018-11-24 03:23 UTC, anovis requested changes
we should add support for these features for quasiparticles as well. this can be done by allowing this to be configured in the pcf_field which then calls each particles apply function.

2018-11-24 03:23 UTC, anovis commented on pcf/core/particle.py
> +                    if max_timeout and (time.time() - start_timeout) >= max_timeout:
i think we only need this check once per while loop and should be done before any logic happens.

2018-11-27 16:34 UTC, ethanwlo requested changes
Need to add unit tests.

2018-12-17 23:53 UTC, emr0327 commented
@anovis @bb1314 please review revisions

2018-12-18 15:21 UTC, anovis commented
can you add this for quasiparticles as well. it should just be a passthrough in the quasiparticle apply.

2018-12-18 16:37 UTC, emr0327 commented
sure thing!

2018-12-19 16:17 UTC, anovis requested changes
hey the tests are failing for me. did you run with pytest ?

2018-12-19 16:17 UTC, anovis commented on pcf/test/core/test_quasiparticle.py
> +        test_quasiparticle.apply(max_timeout=2)g
typo. "g" at the end of the line.

2019-01-04 14:01 UTC, anovis commented
the tests still fail. looks like it just goes straight to the assert False statement and doesnt catch the max timeout exception.

2019-01-04 14:12 UTC, anovis commented
i think your problem is that you are using the `ParticlePassingVars` class which is from a diferent test suite. that automatically sets the state to running so it skips the while loop where the max timeout is happening. i would choose a different class or create your own for the test. @emr0327

2019-01-09 15:14 UTC, anovis requested changes
awesome looks good. these small changes should fix it.

2019-01-09 15:14 UTC, anovis commented on pcf/test/core/test_quasiparticle.py
> +class QuasiParticleTest(Particle):
can you change this to `TestMaxTimeout`

2019-01-09 15:14 UTC, anovis commented on pcf/test/core/test_quasiparticle.py
> +    flavor = "quasiparticle_flavor"
flavor should be quasiparticle

2019-01-09 16:48 UTC, emr0327 commented
@anovis please review requested changes

2019-01-10 14:20 UTC, anovis approved these changes

2019-01-10 14:22 UTC, merged